AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to create static website
Resources:
  WebServerSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: My security group to allow access on ports 80 and 22
      GroupName: MyWebServer-01
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 172.31.0.0/16
      Tags:
        - Key: Name
          Value: MyWebServer SG
      VpcId: vpc-0a4ccbba02c46da2b
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SubnetId: subnet-0310c2a1f4cc62675
      SecurityGroupIds:
        - !Ref WebServerSG
      KeyName: cloudformation-key
      ImageId: ami-0fa1ca9559f1892ec
      Tags:
        - Key: cloudformation-key
          Value: MyWebServer
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          sudo su
          yum update -y
          yum install -y httpd
          cd /var/www/html
          wget https://github.com/azeezsalu/techmax/archive/refs/heads/main.zip
          unzip main.zip
          cp -r techmax-main/* /var/www/html/
          rm -rf techmax-main main.zip
          systemctl enable httpd 
          systemctl start httpd
